//Menggunakan REST Client Untuk Testing API Endpoint

//Menampilkan semua data product
GET http://localhost:3000/products

###

//Menampilkan data product berdasarkan id
GET http://localhost:3000/products/1

###

//Menambah data product
POST http://localhost:3001/products
Content-Type: application/json

{
    "title": "Buku Gambar",
    "price": 2000,
    "stock": "as"
}

###

//Mengedit data product
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
    "title": "Pensil",
    "price": 500
}

###

//Menghapus data product
DELETE http://localhost:3000/products/4